
server:
  address: 0.0.0.0
  port: 9880
  servlet:
    contextPath: /

logging:
  config: classpath:logback.xml
  level:
    org.springframework.security: DEBUG

spring:
  data:
    neo4j:
      username: neo4j
      password: secret

