
server:
  address: 0.0.0.0
  port: 9080
  servlet:
    contextPath: /admin-data

logging:
  config: classpath:logback.xml
  level:
    org.springframework.security: DEBUG

spring:
  data:
    neo4j:
      username: neo4j
      password: secret
      auto-index: none
      uri: bolt://7687


