server:
  address: 0.0.0.0
  port: 8080
  servlet:
    contextPath: /admin

security:
# deprecated
  basic:
    enabled: true
  user:
    name: user
    password: password
    roles: USER
  ignored:
  - "*.bundle.*"
  oauth2:
#    client:
#      clientId: bd1c0a783ccdd1c9b9e4
#      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://api.github.com/user
    client:
      client-id: adminclient
      client-secret: adminclientsecret
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
    resource:
      user-info-uri: http://localhost:9999/uaa/user


logging:
  config: classpath:logback.xml
  level:
    org.springframework.security: DEBUG
